### ISSUE TITLE
Исправление проблем в ossi.py

### ISSUE THREAD

**Issue by oldstream** [ISKhomutov/python-ossi#1]
Во-первых, спасибо. Мне ваш класс здорово помог. :) Теперь о найденных багах:
1) Правки в строке 12:
END  = '\n' + EOF + '\n'
Я столкнулся с ситуацией, когда в середине вывода появлялась комбинация EOF + '\n'.
2) Правки в строке 92:
for i in range(min(len(parse['fields']), len(parse['data']))):
При несовпадении длин возникает исключение при попытке доступа к элементу словаря. Хотя сейчас я уже думаю, что возможно проблема возникала вследствие 1).

**Comment by ikhomutov** [comment]
Добрый день. Рад был помочь)
Да, в то время я только начинал работать с python и, оглядываясь назад, понимаю как все плохо с кодом) но сейчас я уже не занимаюсь сопровождением телефонии и avaya, и не думаю что буду исправлять этот скрипт.
